---

- name: Upgrade system
  become: yes
  apt: upgrade=dist update_cache=yes

- name: Remove default nginx config
  become: yes
  file: name=/etc/nginx/sites-enabled/default state=absent

- name: Setup nginx backend API conf
  become: yes
  template:
    src: "nginx/django.conf"
    dest: "/etc/nginx/sites-available/app_django"

- name: Enable the nginx backend API
  become: yes
  file:
    src: "/etc/nginx/sites-available/app_django"
    dest: "/etc/nginx/sites-enabled/app_django"
    state: link
  notify:
    - reload nginx

- name: "Just force nginx to reload"
  shell: "{{ item }}"
  with_items:
    - sudo gpasswd -a www-data ubuntu
    - sudo systemctl restart nginx
