---

- name: enable postgresql
  service: name=postgresql enabled=yes

- name: start postgresql
  service: name=postgresql state=started

- name: stop postgresql
  service: name=postgresql state=stopped

- name: restart postgresql
  service: name=postgresql state=restarted

- name: reload postgresql
  service: name=postgresql state=reloaded
