---

# - name: install letsencrypt
#   become: yes
#   apt: name=letsencrypt state=latest

# - name: create letsencrypt directory
#   become: yes
#   file: name=/var/www/letsencrypt state=directory

# - name: Ensure nginx service is started
#   service:
#     name: nginx
#     state: started
#     enabled: yes

- name: Remove default nginx config
  become: yes
  file: name=/etc/nginx/sites-enabled/default state=absent

# - name: Install nginx site for letsencrypt requests
#   become: yes
#   template:
#     src: "nginx/nginx-http.conf"
#     dest: "/etc/nginx/sites-enabled/http"
#   notify:
#     - reload nginx

# - name: Create letsencrypt certificate
#   become: yes
#   shell: letsencrypt certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }}
#   args:
#     creates: /etc/letsencrypt/live/{{ domain_name }}

# - name: Generate dhparams
#   become: yes
#   shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
#   args:
#     creates: /etc/nginx/dhparams.pem

- name: Setup nginx django backend HTTP and Static
  become: yes
  template:
    src: "nginx/{{ nginx_conf }}.conf"
    dest: "/etc/nginx/sites-available/{{ nginx_conf }}_{{ repo_gh_version }}"

- name: Enable the nginx conf
  become: yes
  file:
    src: "/etc/nginx/sites-available/{{ nginx_conf }}_{{ repo_gh_version }}"
    dest: "/etc/nginx/sites-enabled/{{ nginx_conf }}_{{ repo_gh_version }}"
    state: link

# - name: Add letsencrypt cronjob for cert renewal
#   become: yes
#   cron:
#     name: letsencrypt_renewal
#     special_time: weekly
#     job: letsencrypt --renew certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }} && service nginx reload

- name: Just force nginx to reload
  shell: sudo systemctl restart nginx
